[tool.poetry]
name = "test-gh-actions"
version = "0.1.17"
description = "description test 1"
authors = ["Shalev Avhar <shalev@getport.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

