name: Create Release

on:
  push:
    tags:
        - "v*"

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Create a release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }} # Use the name of the created tag
          release_name: "Release ${{ github.ref_name }}"
          body: |
            Automated release created for version ${{ github.ref_name }}.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
